### PR TITLE
Fix wrong variable name in signal handler introduced in 8aa0300

### LINKED ISSUE #678: Canceling an inspection fails with an unexpected error
Pressing `Ctrl-C` during inspection resulted in this error:

```
^CMachinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.4.0.20150309T155224ZopenSUSE131gitbfc420c/plugins/inspect/unmanaged_files_inspector.rb:363:in `rescue in inspect': undefined local variable or method `tmp_file_store' for #<UnmanagedFilesInspector:0x00000002f20330> (NameError)
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.4.0.20150309T155224ZopenSUSE131gitbfc420c/plugins/inspect/unmanaged_files_inspector.rb:342:in `inspect'
        from /usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.4.0.20150309T155224ZopenSUSE131gitbfc420c/lib/inspect_task.rb:95:in `block in build_description'
...
```

It should instead exit without any message or with a message "Execution of machinery aborted." or something like that.

The `undefined local variable` also seems to indicate that the exception handling of this particular code has some issues.

### PR DESCRIPTION
**Pull request by aduffeck**
Fixes #678

### CODE REVIEW

**Comment by cornelius** [comment]
lgtm
